import { PLAYER } from '../constants/game.constants';
import { COMBAT_CONFIG } from '../data/combatConfig';
import { PLAYER_ATTACKS, PLAYER_COUNTER_ATTACK, PLAYER_SKILL_ATTACK } from '../data/playerAttacks';
import { ENEMY_ATTACKS } from '../data/enemyAttacks';
import { AttackController } from './AttackController';
import { AttackDirector } from './AttackDirector';
import { ComboSystem } from './ComboSystem';
import { CounterSystem } from './CounterSystem';
import { DamageSystem } from './DamageSystem';
import { DodgeSystem } from './DodgeSystem';
import { HitDetectionSystem } from './HitDetectionSystem';
import type { Enemy } from '../actors/Enemy';
import type { Player } from '../actors/Player';
import type { AttackDefinition } from './combat.types';
export class BasicCombatController { comboSystem=new ComboSystem(); playerAttack=new AttackController(); counter=new CounterSystem(); dodge=new DodgeSystem(); director=new AttackDirector(); combo=0; score=0; skillCooldown=0; private hitDetect=new HitDetectionSystem(); private damage=new DamageSystem(); private enemyAttacks=new Map<string, AttackController>(); constructor(private scene: Phaser.Scene) {}
  update(player: Player, enemies: Enemy[], delta: number, now: number): void { this.playerAttack.update(delta); this.counter.update(delta); this.dodge.update(delta); this.director.update(delta); this.comboSystem.update(delta); this.skillCooldown=Math.max(0,this.skillCooldown-delta); if(this.dodge.invulnerable) player.invulnerableMs=Math.max(player.invulnerableMs,40); if(this.playerAttack.phase==='complete') { player.stateMachine.transition('recovering',80); this.playerAttack.reset(); }
    this.resolvePlayerHits(player,enemies,now); enemies.forEach(e=>this.updateEnemyAttack(e,player,delta,now)); this.combo=this.comboSystem.index; }
  requestAttack(player: Player): void { if(this.counter.consume()){ this.startPlayerAttack(player,PLAYER_COUNTER_ATTACK,'countering'); return; } this.comboSystem.bufferInput(); const next=this.comboSystem.choose(this.playerAttack.current,this.playerAttack.elapsedMs,PLAYER_ATTACKS); if(next && !this.playerAttack.current) { this.comboSystem.commitFirst(); this.startPlayerAttack(player,next,'attacking'); } else if(next && this.playerAttack.phase==='recovery') { this.startPlayerAttack(player,next,'attacking'); } }
  requestSkill(player: Player): void { if(this.skillCooldown>0 || this.playerAttack.isBusy) return; this.skillCooldown=PLAYER.skillCooldown; this.startPlayerAttack(player,PLAYER_SKILL_ATTACK,'attacking'); const ring=this.scene.add.image(player.x,player.y,'skill-ring').setDepth(999).setAlpha(.75); this.scene.tweens.add({targets:ring,scale:1.35,alpha:0,duration:260,onComplete:()=>ring.destroy()}); }
  requestDodge(player: Player, input: {moveX:number; moveY:number}): void { if(!this.dodge.start()) return; if(player.stateMachine.state==='stunned'||player.stateMachine.state==='knockedDown') return; if(player.stateMachine.state==='attacking' && !this.playerAttack.current?.canDodgeCancelRecovery) return; this.comboSystem.reset(); this.playerAttack.reset(); player.stateMachine.transition('dodging',COMBAT_CONFIG.dodgeStartupMs+COMBAT_CONFIG.dodgeInvulnerabilityMs+COMBAT_CONFIG.dodgeRecoveryMs,{invulnerable:true}); const dir=new Phaser.Math.Vector2(input.moveX,input.moveY); if(dir.lengthSq()===0) dir.copy(player.facing); else dir.normalize(); player.setVelocity(dir.x*PLAYER.dodgeSpeed,dir.y*PLAYER.dodgeSpeed); }
  startEnemyTelegraph(enemy: Enemy): boolean { if(!this.director.request(enemy.id, enemy.variant)) return false; enemy.aiState='Telegraph'; const a=ENEMY_ATTACKS[enemy.variant]; enemy.telegraph?.destroy(); enemy.telegraph=this.scene.add.graphics().setDepth(enemy.y-1); enemy.telegraph.fillStyle(a.unblockable?0xff3030:0xffb347,0.22).fillEllipse(enemy.x+enemy.facing.x*42,enemy.y+enemy.facing.y*42,100,58); enemy.telegraph.lineStyle(2,a.unblockable?0xffffff:0xffdc8a,0.8).strokeTriangle(enemy.x,enemy.y,enemy.x+enemy.facing.x*82-enemy.facing.y*20,enemy.y+enemy.facing.y*82+enemy.facing.x*20,enemy.x+enemy.facing.x*82+enemy.facing.y*20,enemy.y+enemy.facing.y*82-enemy.facing.x*20); this.scene.time.delayedCall(a.telegraphMs ?? 400,()=>{ if(enemy.active){ enemy.telegraph?.destroy(); enemy.aiState='Attack'; const c=this.enemyController(enemy); c.start(a); enemy.stateMachine.transition('attacking'); }}); return true; }
  resetCombo(): void { this.comboSystem.reset(); this.combo=0; } reset(): void { this.resetCombo(); this.score=0; this.director.reset(); }
  private startPlayerAttack(player: Player, attack: AttackDefinition, state:'attacking'|'countering'): void { this.playerAttack.reset(); this.playerAttack.start(attack); player.stateMachine.transition(state, attack.startupMs+attack.activeMs+attack.recoveryMs,{superArmor:attack.superArmorDuringActive}); }
  private resolvePlayerHits(player: Player, enemies: Enemy[], _now:number): void { const attack=this.playerAttack.current; if(!attack) return; const targets=enemies.map(e=>e.runtime()); for(const hit of this.hitDetect.query(player.runtime(),attack,targets,id=>this.playerAttack.canHit(id))){ const enemy=enemies.find(e=>e.id===hit.id); if(!enemy) continue; const event=this.damage.resolve(player.runtime(),hit,attack,Infinity); enemy.applyRuntime(hit); enemy.receiveKnockback(new Phaser.Math.Vector2(player.x,player.y),attack.knockback); for(const st of attack.appliesStatus ?? []) { if(st.type==='stun') enemy.stateMachine.transition('stunned', st.durationMs*(1-hit.resistance.stun)); if(st.type==='airborne') enemy.stateMachine.transition('airborne', st.durationMs*(1-hit.resistance.airborne)); if(st.type==='knockdown') enemy.stateMachine.transition('knockedDown', st.durationMs*(1-hit.resistance.knockdown)); } this.playerAttack.markHit(enemy.id); this.score+=100*(this.comboSystem.index+1); this.impact(enemy.x,enemy.y,event.damage); if(event.damage>0)this.scene.cameras.main.shake(attack.hitStopMs,.0025); } }
  private updateEnemyAttack(enemy: Enemy, player: Player, delta:number, now:number): void { const c=this.enemyController(enemy); c.update(delta); if(c.phase==='complete'){ c.reset(); this.director.release(enemy.id); enemy.aiState='Recover'; enemy.attackCooldown=enemy.config.attackCooldown; enemy.stateMachine.transition('recovering',220); } const attack=c.current; if(!attack) return; for(const hit of this.hitDetect.query(enemy.runtime(),attack,[player.runtime()],id=>c.canHit(id))){ const event=this.damage.resolve(enemy.runtime(),hit,attack,now-player.blockStartedAt); player.applyRuntime(hit); c.markHit(player.id); if(event.perfectBlocked){ this.counter.open(); enemy.stateMachine.transition('stunned',260); } else if(event.damage>0) this.resetCombo(); this.impact(player.x,player.y,event.damage,event.perfectBlocked?'PERFECT':event.blocked?'BLOCK':''); } }
  private enemyController(enemy: Enemy): AttackController { let c=this.enemyAttacks.get(enemy.id); if(!c){ c=new AttackController(); this.enemyAttacks.set(enemy.id,c); } return c; }
  private impact(x:number,y:number,damage:number,label=''):void{ const t=this.scene.add.text(x,y-42,label || String(damage),{fontSize:'18px',color:label==='PERFECT'?'#aef':'#ffd166'}).setDepth(1000); this.scene.tweens.add({targets:t,y:y-75,alpha:0,duration:420,onComplete:()=>t.destroy()}); }
}
