import { PLAYER } from '../constants/game.constants';
import { COMBAT_CONFIG } from '../data/combatConfig';
import { ENEMY_ATTACKS } from '../data/enemyAttacks';
import { KAEL_ATTACKS, KAEL_COUNTER_ATTACK } from '../characters/kael/kael.attacks';
import { KAEL_SKILLS } from '../characters/kael/kael.skills';
import { KAEL_DEFINITION } from '../characters/kael/kael.definition';
import { AttackController } from './AttackController';
import { AttackDirector } from './AttackDirector';
import { ComboSystem } from './ComboSystem';
import { CounterSystem } from './CounterSystem';
import { DamageSystem } from './DamageSystem';
import { DodgeSystem } from './DodgeSystem';
import { HitDetectionSystem } from './HitDetectionSystem';
import { SkillController } from '../skills/SkillController';
import { SkillLoadout } from '../skills/SkillLoadout';
import { KaelMomentumSystem } from '../characters/kael/KaelMomentumSystem';
import type { Enemy } from '../actors/Enemy';
import type { Player } from '../actors/Player';
import type { AttackDefinition, CombatStatusType } from './combat.types';
export class BasicCombatController { comboSystem=new ComboSystem(); playerAttack=new AttackController(); counter=new CounterSystem(); dodge=new DodgeSystem(); director=new AttackDirector(); skills=new SkillController(new SkillLoadout(KAEL_DEFINITION.equippedSkillIds,KAEL_SKILLS)); momentum=new KaelMomentumSystem((e,p)=>this.scene.events.emit(e,p)); combo=0; score=0; skillCooldown=0; contextual?:{enemy:Enemy; attack:AttackDefinition; status:CombatStatusType}; private hitDetect=new HitDetectionSystem(); private damage=new DamageSystem(); private enemyAttacks=new Map<string, AttackController>(); private momentumGranted=new Set<string>(); constructor(private scene: Phaser.Scene, private attacks:AttackDefinition[]=KAEL_ATTACKS) {}
  update(player: Player, enemies: Enemy[], delta: number, now: number): void { this.playerAttack.update(delta); this.skills.update(delta); this.counter.update(delta); this.dodge.update(delta); this.director.update(delta); this.comboSystem.update(delta); this.momentum.update(delta); this.skillCooldown=this.skills.active?this.skills.cooldowns.get(this.skills.active.id):0; if(this.dodge.invulnerable) player.invulnerableMs=Math.max(player.invulnerableMs,40); if(this.playerAttack.phase==='complete') { player.stateMachine.transition('recovering',80); this.playerAttack.reset(); this.momentumGranted.clear(); } if(this.skills.attack.phase==='complete'){ player.stateMachine.transition('recovering',80); this.skills.cancel(); this.momentumGranted.clear(); }
    this.contextual=this.findContextual(player,enemies); this.resolvePlayerHits(player,enemies,now); enemies.forEach(e=>this.updateEnemyAttack(e,player,delta,now)); this.combo=this.comboSystem.index; }
  requestAttack(player: Player): void { if(!player.canAttack) return; if(this.contextual){ this.startPlayerAttack(player,this.contextual.attack,'attacking'); this.comboSystem.reset(); this.scene.events.emit('contextual:started',{attackId:this.contextual.attack.id,targetId:this.contextual.enemy.id}); return; } if(this.counter.consume()){ this.startPlayerAttack(player,KAEL_COUNTER_ATTACK,'countering'); return; } this.comboSystem.bufferInput(); const comboAttacks=KAEL_DEFINITION.basicCombo.map(id=>this.attackById(id)); const next=this.comboSystem.choose(this.playerAttack.current,this.playerAttack.elapsedMs,comboAttacks); if(next && !this.playerAttack.current) { this.comboSystem.commitFirst(); this.startPlayerAttack(player,next,'attacking'); } else if(next && this.playerAttack.phase==='recovery') { this.startPlayerAttack(player,next,'attacking'); } }
  requestSkill(player: Player, slot=0): void { if(!player.canAttack || this.playerAttack.isBusy || this.skills.attack.isBusy) return; const skill=this.skills.tryStart(slot,this.momentum.getMultipliers().cooldown); if(!skill) return; player.stateMachine.transition('attacking', skill.startupMs+skill.activeMs+skill.recoveryMs,{superArmor:skill.superArmorDuringActive}); this.scene.events.emit('skill:started',{skillId:skill.id}); this.showSkillEffect(player.x,player.y,skill.visualEffectId); }
  requestDodge(player: Player, input: {moveX:number; moveY:number}): void { if(player.stateMachine.state==='dead') return; if(!this.dodge.start()) return; if(player.stateMachine.state==='stunned'||player.stateMachine.state==='knockedDown') return; if(player.stateMachine.state==='attacking' && !this.playerAttack.current?.canDodgeCancelRecovery) return; this.comboSystem.reset(); this.playerAttack.reset(); this.skills.cancel(); player.stateMachine.transition('dodging',COMBAT_CONFIG.dodgeStartupMs+COMBAT_CONFIG.dodgeInvulnerabilityMs+COMBAT_CONFIG.dodgeRecoveryMs,{invulnerable:true}); const dir=new Phaser.Math.Vector2(input.moveX,input.moveY); if(dir.lengthSq()===0) dir.copy(player.facing); else dir.normalize(); player.setVelocity(dir.x*PLAYER.dodgeSpeed,dir.y*PLAYER.dodgeSpeed); }
  startEnemyTelegraph(enemy: Enemy, targetAlive=true): boolean { if(!targetAlive || enemy.stateMachine.state==='dead') return false; if(!this.director.request(enemy.id, enemy.variant)) return false; enemy.aiState='Telegraph'; const a=ENEMY_ATTACKS[enemy.variant]; enemy.telegraph?.destroy(); enemy.telegraph=this.scene.add.graphics().setDepth(enemy.y-1); enemy.telegraph.fillStyle(a.unblockable?0xff3030:0xffb347,0.22).fillEllipse(enemy.x+enemy.facing.x*42,enemy.y+enemy.facing.y*42,100,58); enemy.telegraph.lineStyle(2,a.unblockable?0xffffff:0xffdc8a,0.8).strokeTriangle(enemy.x,enemy.y,enemy.x+enemy.facing.x*82-enemy.facing.y*20,enemy.y+enemy.facing.y*82+enemy.facing.x*20,enemy.x+enemy.facing.x*82+enemy.facing.y*20,enemy.y+enemy.facing.y*82-enemy.facing.x*20); this.scene.time.delayedCall(a.telegraphMs ?? 400,()=>{ if(enemy.active && enemy.stateMachine.state!=='dead'){ enemy.telegraph?.destroy(); enemy.aiState='Attack'; const c=this.enemyController(enemy); c.start(a); enemy.stateMachine.transition('attacking'); }}); return true; }
  resetCombo(): void { this.comboSystem.reset(); this.combo=0; } onPlayerDefeated(): void { this.resetCombo(); this.playerAttack.reset(); this.skills.reset(); this.counter.reset(); this.dodge.reset(); this.director.reset(); this.enemyAttacks.forEach(c=>c.reset()); this.momentum.onDeath(); this.contextual=undefined; }
  get activeHitboxCount(): number { let count=this.playerAttack.phase==='active'?1:0; count+=this.skills.attack.phase==='active'?1:0; this.enemyAttacks.forEach(c=>{ if(c.phase==='active') count+=1; }); return count; } enemyAttackId(id:string): string { return this.enemyAttacks.get(id)?.current?.id ?? 'none'; } reset(): void { this.resetCombo(); this.score=0; this.playerAttack.reset(); this.skills.reset(); this.counter.reset(); this.dodge.reset(); this.director.reset(); this.enemyAttacks.clear(); this.momentum.reset(); this.contextual=undefined; }
  private startPlayerAttack(player: Player, attack: AttackDefinition, state:'attacking'|'countering'): void { this.playerAttack.reset(); this.skills.cancel(); this.playerAttack.start(attack); player.stateMachine.transition(state, attack.startupMs+attack.activeMs+attack.recoveryMs,{superArmor:attack.superArmorDuringActive}); this.scene.events.emit('combat:attack-started',{attackId:attack.id}); }
  private activePlayerController():AttackController{ return this.skills.attack.current?this.skills.attack:this.playerAttack; }
  private resolvePlayerHits(player: Player, enemies: Enemy[], _now:number): void { const controller=this.activePlayerController(); const attack=controller.current; if(!attack) return; const targets=enemies.map(e=>e.runtime()); for(const hit of this.hitDetect.query(player.runtime(),attack,targets,id=>controller.canHit(id))){ const enemy=enemies.find(e=>e.id===hit.id); if(!enemy) continue; const event=this.damage.resolve(player.runtime(),hit,attack,Infinity); enemy.applyRuntime(hit); if(enemy.stateMachine.state==='dead') this.director.release(enemy.id); enemy.receiveKnockback(new Phaser.Math.Vector2(player.x,player.y),attack.knockback); this.applyStatuses(enemy,attack); controller.markHit(enemy.id); this.grantMomentum(attack); this.score+=100*(this.comboSystem.index+1); this.impact(enemy.x,enemy.y,event.damage); if(event.damage>0)this.scene.cameras.main.shake(attack.hitStopMs,.0025); } }
  private grantMomentum(attack:AttackDefinition):void{ if(this.momentumGranted.has(attack.id)) return; this.momentumGranted.add(attack.id); if(attack.id.includes('counter')) this.momentum.onHit('counter'); else if(attack.id.includes('sky')||attack.id.includes('execution')||attack.id.includes('judgment')) this.momentum.onHit('contextual'); else if(this.skills.active?.id===attack.id) this.momentum.onHit('skill'); else if(attack.id==='kael-falling-edge') this.momentum.onHit('finisher'); else this.momentum.onHit('basic'); }
  private applyStatuses(enemy:Enemy, attack:AttackDefinition):void{ for(const st of attack.appliesStatus ?? []) { const dur=st.durationMs*(1-enemy.runtime().resistance[st.type]); if(st.type==='stun') enemy.stateMachine.transition('stunned', dur); if(st.type==='airborne') enemy.stateMachine.transition('airborne', dur); if(st.type==='knockdown') enemy.stateMachine.transition('knockedDown', dur); } }
  private updateEnemyAttack(enemy: Enemy, player: Player, delta:number, now:number): void { const c=this.enemyController(enemy); c.update(delta); if(c.phase==='complete'){ c.reset(); this.director.release(enemy.id); enemy.aiState='Recover'; enemy.attackCooldown=enemy.config.attackCooldown; enemy.stateMachine.transition('recovering',220); } const attack=c.current; if(!attack) return; for(const hit of this.hitDetect.query(enemy.runtime(),attack,[player.runtime()],id=>c.canHit(id))){ const event=this.damage.resolve(enemy.runtime(),hit,attack,now-player.blockStartedAt); player.applyRuntime(hit); if(hit.state==='dead'){ player.die(); this.onPlayerDefeated(); } else if(attack.knockback>0) player.receiveKnockback(new Phaser.Math.Vector2(enemy.x,enemy.y),attack.knockback); c.markHit(player.id); if(event.perfectBlocked){ this.counter.open(); this.momentum.onHit('perfectBlock'); enemy.stateMachine.transition('stunned',260); } else if(event.damage>0){ this.resetCombo(); this.momentum.onDamageTaken(); } if(player.guard<=0 && event.blocked) this.momentum.onGuardBreak(); this.impact(player.x,player.y,event.damage,event.perfectBlocked?'PERFECT':event.blocked?'BLOCK':''); } }
  private findContextual(player:Player,enemies:Enemy[]):BasicCombatController['contextual']{ const statuses:CombatStatusType[]=['airborne','stun','knockdown']; const facing=player.facing; const valid=enemies.filter(e=>e.active && statuses.some(s=>this.statusMatches(e,s))).filter(e=>Phaser.Math.Distance.Between(player.x,player.y,e.x,e.y)<=150).filter(e=>new Phaser.Math.Vector2(e.x-player.x,e.y-player.y).normalize().dot(facing)>0.15).sort((a,b)=>Phaser.Math.Distance.Between(player.x,player.y,a.x,a.y)-Phaser.Math.Distance.Between(player.x,player.y,b.x,b.y)); const enemy=valid[0]; if(!enemy) return undefined; const status=statuses.find(s=>this.statusMatches(enemy,s)); const id=status?KAEL_DEFINITION.contextualAttackIds[status]:undefined; const attack=id?this.attackById(id):undefined; return status&&attack?{enemy,attack,status}:undefined; }
  private statusMatches(e:Enemy,s:CombatStatusType):boolean{ return (s==='stun'&&e.stateMachine.state==='stunned')||(s==='airborne'&&e.stateMachine.state==='airborne')||(s==='knockdown'&&e.stateMachine.state==='knockedDown'); }
  private attackById(id:string):AttackDefinition{ const a=this.attacks.find(v=>v.id===id); if(!a) throw new Error(`Missing attack ${id}`); return a; }
  private enemyController(enemy: Enemy): AttackController { let c=this.enemyAttacks.get(enemy.id); if(!c){ c=new AttackController(); this.enemyAttacks.set(enemy.id,c); } return c; }
  private impact(x:number,y:number,damage:number,label=''):void{ const t=this.scene.add.text(x,y-42,label || String(damage),{fontSize:'18px',color:label==='PERFECT'?'#aef':'#ffd166'}).setDepth(1000); this.scene.tweens.add({targets:t,y:y-75,alpha:0,duration:420,onComplete:()=>t.destroy()}); }
  private showSkillEffect(x:number,y:number,id:string):void{ const key=id==='blade-cyclone'?'skill-ring':'kael-momentum-ring'; const ring=this.scene.add.image(x,y,key).setDepth(999).setAlpha(.65); this.scene.tweens.add({targets:ring,scale:id==='phantom-rush'?0.7:1.35,alpha:0,duration:300,onComplete:()=>ring.destroy()}); }
}
