declare module 'phaser' { export default Phaser; }
declare namespace Phaser {
  const AUTO: number; const BlendModes: { MULTIPLY: number };
  class Game { constructor(config: Types.Core.GameConfig); }
  namespace Types { namespace Core { interface GameConfig { type: number; parent: string; width: number; height: number; backgroundColor: string; physics: unknown; scale: unknown; input: unknown; scene: Array<typeof Scene>; } } namespace Input { namespace Keyboard { interface CursorKeys { up: Input.Keyboard.Key; down: Input.Keyboard.Key; left: Input.Keyboard.Key; right: Input.Keyboard.Key; space: Input.Keyboard.Key; } } } }
  namespace Scale { const FIT: number; const CENTER_BOTH: number; }
  namespace Math { function Between(min:number,max:number): number; function Clamp(v:number,min:number,max:number): number; namespace Distance { function Between(x1:number,y1:number,x2:number,y2:number): number; } class Vector2 { constructor(x?:number,y?:number); x:number; y:number; lengthSq(): number; normalize(): this; copy(v: Vector2): this; clone(): Vector2; scale(n:number): this; add(v: Vector2): this; } }
  namespace Input { namespace Keyboard { class Key { isDown: boolean; } function JustDown(k: Key): boolean; } }
  class Scene { constructor(key?: string); add: GameObjects.GameObjectFactory; physics: Physics.Arcade.ArcadePhysics; input: { keyboard?: { createCursorKeys(): Types.Input.Keyboard.CursorKeys; addKeys(keys:string): unknown }; gamepad?: { total: number; getPad(i:number): { leftStick:{x:number;y:number}; A:boolean; B:boolean; R1:boolean } | undefined } }; textures: { exists(k:string): boolean }; cameras: { main: { shake(duration:number,intensity:number): void } }; tweens: { add(config: Record<string, unknown>): void }; time: { delayedCall(delay:number, cb:()=>void): void }; registry: { set(k:string,v:unknown): void }; scene: { start(k:string): void; restart(): void }; }
  namespace GameObjects { class GameObject { active: boolean; destroy(): void; } class Graphics extends GameObject { fillStyle(c:number,a?:number): this; fillRect(x:number,y:number,w:number,h:number): this; lineStyle(w:number,c:number,a?:number): this; strokeRect(x:number,y:number,w:number,h:number): this; fillEllipse(x:number,y:number,w:number,h:number): this; fillRoundedRect(x:number,y:number,w:number,h:number,r:number): this; strokeRoundedRect(x:number,y:number,w:number,h:number,r:number): this; fillCircle(x:number,y:number,r:number): this; fillTriangle(x1:number,y1:number,x2:number,y2:number,x3:number,y3:number): this; strokeCircle(x:number,y:number,r:number): this; generateTexture(k:string,w:number,h:number): void; } class Image extends GameObject { x:number; y:number; constructor(scene:Scene,x:number,y:number,key:string); setDepth(d:number): this; setTint(t:number): this; setY(y:number): this; setScale(s:number): this; setAlpha(a:number): this; setBlendMode(m:number): this; } class Text extends GameObject { setOrigin(x:number,y?:number): this; } class Rectangle extends Image {} class GameObjectFactory { graphics(): Graphics; existing(o:unknown): void; image(x:number,y:number,k:string): Image; text(x:number,y:number,t:string,s?:Record<string,string>): Text; rectangle(x:number,y:number,w:number,h:number,c:number,a?:number): Rectangle; } }
  namespace Physics { namespace Arcade { class Body { setSize(w:number,h:number): this; setOffset(x:number,y:number): this; setCircle(r:number): this; } class Sprite extends GameObjects.Image { scene: Scene; body?: Body; setCollideWorldBounds(v:boolean): this; setVelocity(x:number,y?:number): this; setPosition(x:number,y:number): this; disableBody(a:boolean,b:boolean): void; } class StaticGroup { add(o:unknown): void; refresh(): void; } class ArcadePhysics { world: { setBounds(x:number,y:number,w:number,h:number): void }; add: { existing(o:unknown,isStatic?:boolean): void; staticGroup(): StaticGroup; collider(a:unknown,b:unknown): void }; moveToObject(o:unknown,t:unknown,s:number): void; } } }
}
declare module '*.css' { const css: string; export default css; }
declare module 'vitest' { export function describe(name: string, fn: () => void): void; export function it(name: string, fn: () => void): void; export const expect: (actual: unknown) => { toBe(expected: unknown): void; toBeGreaterThan(expected: number): void; toBeLessThan(expected: number): void }; }
