import { describe, expect, it } from 'vitest';
import { CombatStateMachine } from '../src/game/combat/CombatStateMachine';
import { AttackController } from '../src/game/combat/AttackController';
import { ComboSystem } from '../src/game/combat/ComboSystem';
import { HitDetectionSystem } from '../src/game/combat/HitDetectionSystem';
import { DamageSystem } from '../src/game/combat/DamageSystem';
import { BlockSystem } from '../src/game/combat/BlockSystem';
import { CounterSystem } from '../src/game/combat/CounterSystem';
import { StatusEffectSystem } from '../src/game/combat/StatusEffectSystem';
import { AttackDirector } from '../src/game/combat/AttackDirector';
import { DodgeSystem } from '../src/game/combat/DodgeSystem';
import { PLAYER_ATTACKS } from '../src/game/data/playerAttacks';
import { COMBAT_CONFIG } from '../src/game/data/combatConfig';
import type { CombatRuntime } from '../src/game/combat/combat.types';
const rt=(id:string,x=0,y=0,state:CombatRuntime['state']='idle'):CombatRuntime=>({id,team:id.startsWith('p')?'player':'enemy',health:100,maxHealth:100,guard:100,facing:{x:1,y:0},position:{x,y},state,invulnerableMs:0,superArmorMs:0,airHeight:0,verticalVelocity:0,resistance:{knockback:1,stun:0,airborne:0,knockdown:0}});
describe('stage 2 combat framework',()=>{
 it('allows valid transitions',()=>{const s=new CombatStateMachine(); expect(s.transition('moving')).toBe(true); expect(s.transition('attacking')).toBe(true);});
 it('rejects invalid transitions',()=>{const s=new CombatStateMachine('knockedDown'); expect(s.transition('attacking')).toBe(false);});
 it('advances attack phases',()=>{const c=new AttackController(); c.start(PLAYER_ATTACKS[0]); c.update(100); expect(c.phase).toBe('active'); c.update(100); expect(c.phase).toBe('recovery');});
 it('accepts valid combo window',()=>{const c=new ComboSystem(); c.bufferInput(); expect(c.choose(PLAYER_ATTACKS[0],220,PLAYER_ATTACKS)?.id).toBe('player-attack-2');});
 it('resets combo outside timeout',()=>{const c=new ComboSystem(); c.commitFirst(); c.update(COMBAT_CONFIG.comboTimeoutMs+1); expect(c.index).toBe(0);});
 it('buffers input briefly',()=>{const c=new ComboSystem(); c.bufferInput(); expect(c.hasBufferedInput).toBe(true); c.update(COMBAT_CONFIG.inputBufferMs+1); expect(c.hasBufferedInput).toBe(false);});
 it('prevents duplicate hits from one attack',()=>{const c=new AttackController(); c.start(PLAYER_ATTACKS[0]); c.update(100); expect(c.canHit('e')).toBe(true); c.markHit('e'); expect(c.canHit('e')).toBe(false);});
 it('invulnerability avoids damage',()=>{const d=new DamageSystem(); const t=rt('e'); t.invulnerableMs=10; const e=d.resolve(rt('p'),t,PLAYER_ATTACKS[0]); expect(e.damage).toBe(0);});
 it('front block reduces damage',()=>{const d=new DamageSystem(); const t=rt('p',0,0,'blocking'); const e=d.resolve(rt('e',10,0),t,PLAYER_ATTACKS[0],999); expect(e.blocked).toBe(true); expect(e.damage).toBeLessThan(PLAYER_ATTACKS[0].damage);});
 it('back attacks ignore block',()=>{const d=new DamageSystem(); const t=rt('p',0,0,'blocking'); const e=d.resolve(rt('e',-10,0),t,PLAYER_ATTACKS[0],999); expect(e.blocked).toBe(false);});
 it('detects perfect block in window',()=>{expect(new BlockSystem().isPerfectBlock(100)).toBe(true);});
 it('detects normal block outside window',()=>{expect(new BlockSystem().isPerfectBlock(300)).toBe(false);});
 it('activates counter',()=>{const c=new CounterSystem(); c.open(); expect(c.consume()).toBe(true);});
 it('expires counter window',()=>{const c=new CounterSystem(); c.open(); c.update(COMBAT_CONFIG.counterWindowMs+1); expect(c.consume()).toBe(false);});
 it('guard never below zero',()=>{const b=new BlockSystem(); const t=rt('p'); b.spendGuard(t,999); expect(t.guard).toBe(0);});
 it('guard never above max',()=>{const b=new BlockSystem(); const t=rt('p'); b.regenGuard(t,9999); expect(t.guard).toBe(COMBAT_CONFIG.guardMax);});
 it('applies and expires stun through state machine',()=>{const s=new CombatStateMachine(); s.transition('stunned',10); s.update(11); expect(s.state).toBe('recovering');});
 it('runs airborne to knockdown',()=>{const sys=new StatusEffectSystem(); const t=rt('e'); sys.apply(t,{type:'airborne',durationMs:100}); t.airHeight=1; t.verticalVelocity=1; sys.update(t,2); expect(t.state).toBe('knockedDown');});
 it('models heavy resistance values',()=>{const heavy=rt('e'); heavy.resistance.stun=.55; expect(100*(1-heavy.resistance.stun)).toBeLessThan(100);});
 it('director respects attacker limit',()=>{const a=new AttackDirector(); expect(a.request('n1','normal')).toBe(true); a.update(999); expect(a.request('n2','normal')).toBe(true); a.update(999); expect(a.request('n3','normal')).toBe(false);});
 it('director releases slots',()=>{const a=new AttackDirector(); a.request('h1','heavy'); a.release('h1'); expect(a.request('h2','heavy')).toBe(true);});
 it('cooldowns do not go below zero',()=>{const d=new DodgeSystem(); d.start(); d.update(999999); expect(d.cooldownMs).toBe(0);});
 it('hit detection uses hitboxes',()=>{const h=new HitDetectionSystem(); expect(h.query(rt('p'),{...PLAYER_ATTACKS[0],hitbox:{shape:'circle',offsetX:0,offsetY:0,radius:50}},[rt('e',40,0)],()=>true).length).toBe(1);});
});
