import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { assetManifest, KAEL_REQUIRED_ANIMATIONS, getAnimation } from '../src/game/assets/assetManifest';
import { KAEL_ATTACKS } from '../src/game/characters/kael/kael.attacks';
import { KAEL_SKILLS } from '../src/game/characters/kael/kael.skills';
const repo=process.cwd(); const allAssets=assetManifest.assets; const allAnimations=allAssets.flatMap(a=>a.animations??[]);
describe('Stage 3.2 raster asset manifest',()=>{
 it('declares critical local assets with unique keys and existing files',()=>{const keys=new Set<string>(); for(const a of allAssets){expect(a.key.length>0).toBe(true); expect(keys.has(a.key)).toBe(false); keys.add(a.key); expect(/^https?:\/\//.test(a.path)).toBe(false); expect(fs.existsSync(path.join(repo,a.path))).toBe(true); if(a.atlasJson) expect(fs.existsSync(path.join(repo,a.atlasJson))).toBe(true);}});
 it('declares Kael, enemies, Asteria, effects, UI, and missing texture',()=>{expect(allAssets.find(a=>a.key==='kael-atlas')?.kind).toBe('spritesheet'); expect(allAssets.find(a=>a.key==='soldier-atlas')?.kind).toBe('spritesheet'); expect(allAssets.find(a=>a.key==='brute-atlas')?.kind).toBe('spritesheet'); expect(allAssets.some(a=>a.key==='asteria-map'&&a.kind==='tilemap')).toBe(true); expect(allAssets.some(a=>a.key==='asteria-tiles')).toBe(true); expect(allAssets.some(a=>a.key==='sword-effects-atlas')).toBe(true); expect(allAssets.some(a=>a.key==='hud-frame')).toBe(true); expect(allAssets.some(a=>a.key==='missing-texture')).toBe(true);});
});
describe('Stage 3.2 animation declarations',()=>{
 it('declares every required Kael animation with valid timing',()=>{for(const key of KAEL_REQUIRED_ANIMATIONS){const anim=getAnimation(key); expect(Boolean(anim)).toBe(true); expect(anim!.frames.length>0).toBe(true); expect(anim!.frameRate>0).toBe(true); expect(anim!.durationMs>=0).toBe(true); if(!/idle|run/.test(key)) expect(anim!.repeat===-1).toBe(false);}});
 it('maps every combo, skill, and contextual attack to an animation',()=>{for(const a of KAEL_ATTACKS) expect(Boolean(getAnimation(a.id))).toBe(true); for(const s of KAEL_SKILLS) expect(Boolean(getAnimation(s.id))).toBe(true);});
 it('declares enemy telegraph and attack animations',()=>{for(const key of ['soldier-telegraph','soldier-attack','brute-telegraph','brute-heavy-attack','brute-unblockable-attack']) expect(Boolean(getAnimation(key))).toBe(true);});
});
describe('Stage 3.2 combat sync and dual wield metadata',()=>{
 it('keeps active frames inside startup and recovery bounds',()=>{for(const anim of allAnimations.filter(a=>a.sync)){const s=anim.sync!; expect(s.activeStartFrame>=s.startupEndFrame).toBe(true); expect(s.activeEndFrame<=s.recoveryEndFrame).toBe(true); for(const h of s.hitFrames??[]){expect(h>=s.activeStartFrame).toBe(true); expect(h<=s.activeEndFrame).toBe(true);} expect(s.fallbackMs>0).toBe(true);}});
 it('declares requested multi-hit markers and finishSkill authority',()=>{expect(getAnimation('kael-cross-cut')!.sync!.hitFrames!.length).toBe(2); expect(getAnimation('kael-rising-tempest')!.sync!.hitFrames!.length).toBe(2); expect(getAnimation('kael-phantom-rush')!.sync!.hitFrames!.length).toBe(3); expect(getAnimation('kael-blade-cyclone')!.sync!.hitFrames!.length<5).toBe(true); expect(getAnimation('kael-falling-edge')!.sync!.hitFrames!.includes(43)).toBe(true); expect(getAnimation('kael-rising-tempest')!.sync!.finishSkillAuthoritative).toBe(true);});
 it('declares dual-wield visibility and hands',()=>{expect((getAnimation('kael-idle-down')!.visibleWeapons??[]).join(',')).toBe('left,right'); expect(getAnimation('kael-twin-slash-1')!.actionHand).toBe('right'); expect(getAnimation('kael-twin-slash-2')!.actionHand).toBe('left'); for(const key of ['kael-cross-cut','kael-block','kael-counter','kael-rising-tempest','kael-blade-cyclone']) expect(getAnimation(key)!.actionHand ?? 'both').toBe('both');});
});
describe('Stage 3.2 tilemap and primitive guardrails',()=>{
 it('has required tilemap layers and objects without invalid tile ids',()=>{const m=JSON.parse(fs.readFileSync(path.join(repo,'assets/environments/asteria/asteria-map.json'),'utf8')); const names=m.layers.map((l:{name:string})=>l.name); for(const n of ['Collision','Actor layer','High props','Objects']) expect(names.includes(n)).toBe(true); const objs=m.layers.find((l:{name:string})=>l.name==='Objects').objects; expect(objs.some((o:{name:string})=>o.name==='SanctuaryDoorCollision')).toBe(true); expect(objs.some((o:{name:string})=>o.name==='PlayerSpawn')).toBe(true); expect(objs.filter((o:{type:string})=>o.type==='enemy').length>0).toBe(true); for(const l of m.layers.filter((l:{data?:number[]})=>l.data)) for(const id of l.data) expect(id<=m.tilesets[0].tilecount).toBe(true);});
 it('does not create gameplay Graphics in core visible runtime files',()=>{for(const file of ['src/game/scenes/CombatScene.ts','src/game/world/AsteriaArena.ts','src/game/actors/Player.ts','src/game/actors/Enemy.ts','src/game/combat/BasicCombatController.ts']){const s=fs.readFileSync(path.join(repo,file),'utf8'); expect(/add\.graphics\(/.test(s)).toBe(false); expect(/generateTexture\(/.test(s)).toBe(false);}});
});
