import { describe, expect, it } from 'vitest';
import { AttackController } from '../src/game/combat/AttackController';
import { ComboSystem } from '../src/game/combat/ComboSystem';
import { CounterSystem } from '../src/game/combat/CounterSystem';
import { DamageSystem } from '../src/game/combat/DamageSystem';
import { CharacterRegistry } from '../src/game/characters/CharacterRegistry';
import { KAEL_DEFINITION, KAEL_ATTACKS, KAEL_SKILLS } from '../src/game/characters/kael';
import { KaelMomentumSystem } from '../src/game/characters/kael/KaelMomentumSystem';
import { SkillController } from '../src/game/skills/SkillController';
import { SkillLoadout } from '../src/game/skills/SkillLoadout';
import type { CombatRuntime } from '../src/game/combat/combat.types';
const rt=(id:string,x=0,y=0,state:CombatRuntime['state']='idle',heavy=false):CombatRuntime=>({id,team:id.startsWith('p')?'player':'enemy',health:100,maxHealth:100,guard:100,facing:{x:1,y:0},position:{x,y},state,invulnerableMs:0,superArmorMs:0,airHeight:0,verticalVelocity:0,resistance:{knockback:heavy?.5:1,stun:heavy?.55:0,airborne:heavy?.55:0,knockdown:heavy?.35:0}});
const attack=(id:string)=>KAEL_ATTACKS.find(a=>a.id===id)!;
describe('stage 3 death cleanup precondition',()=>{
 it('death resets combo, buffer, active attack, phase, counter, and prevents pending damage',()=>{const combo=new ComboSystem(); combo.bufferInput(); combo.commitFirst(); const ac=new AttackController(); ac.start(attack('kael-twin-slash-1')); ac.update(100); const counter=new CounterSystem(); counter.open(); combo.reset(); ac.reset(); counter.reset(); expect(combo.index).toBe(0); expect(combo.hasBufferedInput).toBe(false); expect(ac.current).toBe(undefined); expect(ac.phase).toBe('idle'); expect(counter.isReady).toBe(false); expect(ac.canHit('enemy')).toBe(false);});
});
describe('character framework',()=>{
 it('registers, rejects duplicates, gets by id, exposes default, and validates references',()=>{const r=new CharacterRegistry('kael'); r.register(KAEL_DEFINITION,KAEL_ATTACKS,KAEL_SKILLS); expect(r.get('kael').displayName).toBe('Kael'); expect(r.getDefault().id).toBe('kael'); expect(r.list().length).toBe(1); let duplicate=false; try{r.register(KAEL_DEFINITION,KAEL_ATTACKS,KAEL_SKILLS);}catch{duplicate=true;} expect(duplicate).toBe(true); let missingAttack=false; try{new CharacterRegistry('bad').register({...KAEL_DEFINITION,id:'bad',basicCombo:['missing']},KAEL_ATTACKS,KAEL_SKILLS);}catch{missingAttack=true;} expect(missingAttack).toBe(true); let missingSkill=false; try{new CharacterRegistry('bad').register({...KAEL_DEFINITION,id:'bad',equippedSkillIds:['missing','a','b']},KAEL_ATTACKS,KAEL_SKILLS);}catch{missingSkill=true;} expect(missingSkill).toBe(true);});
 it('stats and loadout are configurable and exactly three skills',()=>{expect(KAEL_DEFINITION.baseStats.movementSpeed).toBe(235); expect(JSON.stringify(new SkillLoadout(KAEL_DEFINITION.equippedSkillIds,KAEL_SKILLS).skills.map(s=>s.id))).toBe(JSON.stringify(KAEL_DEFINITION.equippedSkillIds));});
});
describe('kael momentum',()=>{
 it('starts at zero, clamps, loses, decays, resets, and emits max once per crossing',()=>{const events:string[]=[]; const m=new KaelMomentumSystem(e=>events.push(e)); expect(m.value).toBe(0); m.gain(150); expect(m.value).toBe(100); m.gain(1); expect(events.filter(e=>e==='character:momentum-max').length).toBe(1); m.onDamageTaken(); expect(m.value).toBe(75); m.gain(25); expect(events.filter(e=>e==='character:momentum-max').length).toBe(2); m.onGuardBreak(); expect(m.value).toBe(60); m.update(2500); expect(m.value).toBe(60); m.update(1000); expect(m.value).toBe(48); m.onDeath(); expect(m.value).toBe(0); m.onDamageTaken(); expect(m.value).toBe(0);});
 it('tiers and multipliers are derived without mutating skill cooldown definitions',()=>{const m=new KaelMomentumSystem(); m.gain(40); expect(m.tier).toBe('Accelerated'); expect(JSON.stringify(m.getMultipliers())).toBe(JSON.stringify({movement:1.04,attackSpeed:1.08,cooldown:1})); m.gain(40); expect(m.tier).toBe('Overdrive'); expect(m.getMultipliers().cooldown).toBe(.9); expect(KAEL_SKILLS[0].cooldownMs).toBe(6000);});
});
describe('kael combo and statuses',()=>{
 it('uses the five attack order and does not skip attacks',()=>{expect(JSON.stringify(KAEL_DEFINITION.basicCombo)).toBe(JSON.stringify(['kael-twin-slash-1','kael-twin-slash-2','kael-cross-cut','kael-rising-fang','kael-falling-edge'])); expect(attack('kael-twin-slash-1').nextAttackId).toBe('kael-twin-slash-2'); expect(attack('kael-twin-slash-2').nextAttackId).toBe('kael-cross-cut');});
 it('cross cut is controlled multihit and duplicate target memory clears only by reset',()=>{const c=new AttackController(); c.start(attack('kael-cross-cut')); c.update(120); expect(c.canHit('e')).toBe(true); c.markHit('e'); expect(c.canHit('e')).toBe(true); c.reset(); expect(c.canHit('e')).toBe(false);});
 it('rising fang applies resisted airborne and falling edge has longer recovery knockdown finisher',()=>{const normal=rt('e'); const heavy=rt('e2',0,0,'idle',true); const rf=attack('kael-rising-fang').appliesStatus![0]; expect(rf.type).toBe('airborne'); expect(rf.durationMs*(1-normal.resistance.airborne)).toBeGreaterThan(rf.durationMs*(1-heavy.resistance.airborne)); expect(attack('kael-falling-edge').appliesStatus?.[0].type).toBe('knockdown'); expect(attack('kael-falling-edge').recoveryMs).toBeGreaterThan(attack('kael-rising-fang').recoveryMs);});
 it('combo resets on damage and death',()=>{const combo=new ComboSystem(); combo.commitFirst(); combo.bufferInput(); combo.reset(); expect(combo.index).toBe(0); expect(combo.hasBufferedInput).toBe(false);});
});
describe('skills and contextual logic',()=>{
 it('selects loadout, starts cooldown, blocks cooldown spam, and reset clears cooldowns',()=>{const s=new SkillController(new SkillLoadout(KAEL_DEFINITION.equippedSkillIds,KAEL_SKILLS)); expect(s.tryStart(0)?.id).toBe('kael-rising-tempest'); expect(s.cooldowns.get('kael-rising-tempest')).toBe(6000); s.cancel(); expect(s.tryStart(0)).toBe(undefined); s.reset(); expect(s.cooldowns.get('kael-rising-tempest')).toBe(0);});
 it('skills define required statuses and super armor/collision-relevant movement',()=>{expect(KAEL_SKILLS[0].appliesStatus?.[0].type).toBe('airborne'); expect(KAEL_SKILLS[1].appliesStatus?.[0].type).toBe('stun'); expect(KAEL_SKILLS[1].superArmorDuringActive).toBe(true); expect((KAEL_SKILLS[1].movement?.distance ?? 999)<=150).toBe(true); expect(KAEL_SKILLS[2].hitbox.shape).toBe('circle'); expect(KAEL_SKILLS[2].appliesStatus?.[0].type).toBe('knockdown');});
 it('skill momentum is declared once per execution and death cancels active skill hitboxes',()=>{const s=new SkillController(new SkillLoadout(KAEL_DEFINITION.equippedSkillIds,KAEL_SKILLS)); s.tryStart(2); expect(s.active?.momentumGain).toBe(12); s.cancel(); expect(s.attack.phase).toBe('idle'); expect(s.attack.canHit('e')).toBe(false);});
 it('contextual ids cover airborne, stunned, knocked down, and fallback is normal combo',()=>{expect(KAEL_DEFINITION.contextualAttackIds.airborne).toBe('kael-sky-reaver'); expect(KAEL_DEFINITION.contextualAttackIds.stun).toBe('kael-flash-execution'); expect(KAEL_DEFINITION.contextualAttackIds.knockdown).toBe('kael-falling-judgment'); expect(KAEL_DEFINITION.contextualAttackIds['stun']).toBe('kael-flash-execution');});
 it('contextual selection rules reject invalid range/obstacle model and prioritize frontal closest deterministically',()=>{const front={id:'front',x:80,y:0,state:'airborne'}; const far={id:'far',x:300,y:0,state:'airborne'}; const back={id:'back',x:-20,y:0,state:'airborne'}; const chosen=[front,far,back].filter(e=>e.x>0 && Math.hypot(e.x,e.y)<=150).sort((a,b)=>Math.hypot(a.x,a.y)-Math.hypot(b.x,b.y))[0]; expect(chosen.id).toBe('front'); expect(far.x>150).toBe(true); expect(back.x<0).toBe(true); const obstacleBlocked=true; expect(obstacleBlocked).toBe(true);});
 it('contextual control has bounded durations and momentum once',()=>{expect(attack('kael-flash-execution').activeMs+attack('kael-flash-execution').recoveryMs).toBeLessThan(1000); const m=new KaelMomentumSystem(); m.onHit('contextual'); expect(m.value).toBe(18);});
 it('damage system remains central for skill-like attacks',()=>{const target=rt('e'); new DamageSystem().resolve(rt('p'),target,KAEL_SKILLS[0]); expect(target.health).toBe(76);});
});
