import { ENEMY } from '../constants/game.constants';
import { CombatStateMachine } from '../combat/CombatStateMachine';
import type { CombatRuntime } from '../combat/combat.types';
import type { EnemyConfig, EnemyVariant } from '../types/game.types';
export class Enemy extends Phaser.Physics.Arcade.Sprite { readonly id:string; readonly team='enemy' as const; readonly variant: EnemyVariant; readonly config: EnemyConfig; health:number; guard=0; facing=new Phaser.Math.Vector2(1,0); stateMachine=new CombatStateMachine(); invulnerableMs=0; superArmorMs=0; airHeight=0; verticalVelocity=0; aiState='Approach'; attackCooldown:number; telegraph?: Phaser.GameObjects.Graphics;
  constructor(scene: Phaser.Scene,x:number,y:number,variant:EnemyVariant,delay:number){const c=ENEMY[variant];super(scene,x,y,`${c.key}-idle`);this.id=`enemy-${variant}-${Math.round(x)}-${Math.round(y)}`;this.variant=variant;this.config=c;this.health=c.maxHealth;this.attackCooldown=delay;scene.add.existing(this);scene.physics.add.existing(this);this.setScale(c.scale).setDepth(y);this.body!.setCircle(20);} 
  updateEnemy(delta:number):void{this.attackCooldown=Math.max(0,this.attackCooldown-delta);this.invulnerableMs=Math.max(0,this.invulnerableMs-delta);this.stateMachine.update(delta); if(this.stateMachine.state==='airborne'){this.airHeight=Math.max(0,this.airHeight-0.08*delta); if(this.airHeight<=0)this.stateMachine.transition('knockedDown',420,{invulnerable:false});} this.y-=0; this.setDepth(this.y); this.setTexture(this.textureForState()); this.setFlipX(this.facing.x<0); if(this.health<=0 && this.active){this.stateMachine.transition('dead'); this.disableBody(true,true); this.telegraph?.destroy();}}
  runtime(): CombatRuntime { return { id:this.id,team:this.team,health:this.health,maxHealth:this.config.maxHealth,guard:this.guard,facing:this.facing,position:this,state:this.stateMachine.state,invulnerableMs:this.invulnerableMs,superArmorMs:this.superArmorMs,airHeight:this.airHeight,verticalVelocity:this.verticalVelocity,resistance:{knockback:this.config.knockbackResistance,stun:this.variant==='heavy'?0.55:0,airborne:this.variant==='heavy'?0.55:0,knockdown:this.variant==='heavy'?0.35:0} }; }
  applyRuntime(r: CombatRuntime):void{this.health=r.health;this.guard=r.guard;this.invulnerableMs=r.invulnerableMs;this.airHeight=r.airHeight;if(this.stateMachine.state!==r.state)this.stateMachine.transition(r.state);} 
  receiveKnockback(from: Phaser.Math.Vector2, power:number):void{const dir=new Phaser.Math.Vector2(this.x-from.x,this.y-from.y).normalize(); this.setVelocity(dir.x*power*this.config.knockbackResistance,dir.y*power*this.config.knockbackResistance);} 
  private textureForState(): string { const base=this.config.key; if(this.stateMachine.state==='attacking'||this.aiState==='Telegraph')return `${base}-attack`; if(this.stateMachine.state==='stunned')return `${base}-stun`; if(this.stateMachine.state==='knockedDown')return `${base}-down`; return `${base}-idle`; }
}
export const enemyConfigFor=(variant:EnemyVariant):EnemyConfig=>ENEMY[variant];
