import { PLAYER } from '../constants/game.constants';
import { COMBAT_CONFIG } from '../data/combatConfig';
import { CombatStateMachine } from '../combat/CombatStateMachine';
import { applyKnockback } from '../combat/knockback';
import type { CombatRuntime } from '../combat/combat.types';
import type { InputState } from '../types/game.types';
export class Player extends Phaser.Physics.Arcade.Sprite { readonly id='player'; readonly team='player' as const; maxHealth: number=PLAYER.maxHealth; health: number=PLAYER.maxHealth; guard: number=COMBAT_CONFIG.guardMax; speed=PLAYER.speed; facing=new Phaser.Math.Vector2(1,0); stateMachine=new CombatStateMachine(); invulnerableMs=0; superArmorMs=0; airHeight=0; verticalVelocity=0; blockStartedAt=-Infinity; private blockHeld=false;
  constructor(scene: Phaser.Scene,x:number,y:number){super(scene,x,y,'player-idle');scene.add.existing(this);scene.physics.add.existing(this);this.setCollideWorldBounds(true).setDepth(y);this.body!.setSize(34,38).setOffset(9,16);this.body!.pushable=false;} 
  updatePlayer(input: InputState, delta: number, now: number): void { if(this.stateMachine.state==='dead'){this.setVelocity(0);this.setTexture(this.textureForState());return;} this.stateMachine.update(delta); this.invulnerableMs=Math.max(0,this.invulnerableMs-delta); this.superArmorMs=Math.max(0,this.superArmorMs-delta); const v=new Phaser.Math.Vector2(input.moveX,input.moveY); if(v.lengthSq()>0){v.normalize(); if(this.stateMachine.state!=='attacking') this.facing.copy(v);} if(input.block && this.canBlock()){ if(!this.blockHeld){this.blockStartedAt=now; this.stateMachine.transition('blocking');} this.blockHeld=true; } else if(this.blockHeld && this.stateMachine.state==='blocking'){ this.stateMachine.transition(v.lengthSq()>0?'moving':'idle'); this.blockHeld=false; }
    const moveAllowed=this.stateMachine.canMove || this.stateMachine.state==='dodging'; const speed=this.stateMachine.state==='blocking'?this.speed*0.35:this.speed; this.setVelocity(moveAllowed?v.x*speed:0, moveAllowed?v.y*speed:0); if(!this.blockHeld) this.guard=Math.min(COMBAT_CONFIG.guardMax,this.guard+COMBAT_CONFIG.guardRegenPerSecond*delta/1000); this.setDepth(this.y); this.setTexture(this.textureForState()); this.setFlipX(this.facing.x<0); this.setAlpha(this.invulnerableMs>0?0.62:1); }
  canBlock(): boolean { return ['idle','moving','blocking'].includes(this.stateMachine.state); }
  get canMove(): boolean { return this.stateMachine.canMove && this.stateMachine.state!=='dead'; }
  get canAttack(): boolean { return this.stateMachine.canAttack && this.stateMachine.state!=='dead'; } receiveDamage(damage:number): boolean { if(this.invulnerableMs>0)return false; this.health=Math.max(0,this.health-damage); if(this.health<=0)this.die(); return true; }
  runtime(): CombatRuntime { return { id:this.id,team:this.team,health:this.health,maxHealth:this.maxHealth,guard:this.guard,facing:this.facing,position:this,state:this.stateMachine.state,invulnerableMs:this.invulnerableMs,superArmorMs:this.superArmorMs,airHeight:this.airHeight,verticalVelocity:this.verticalVelocity,resistance:{knockback:1,stun:0,airborne:0,knockdown:0} }; }
  applyRuntime(r: CombatRuntime): void { this.health=r.health; this.guard=r.guard; this.invulnerableMs=r.invulnerableMs; if(this.stateMachine.state!==r.state)this.stateMachine.transition(r.state); }
  die(): void { if(this.stateMachine.state==='dead') return; this.health=0; this.guard=0; this.invulnerableMs=0; this.superArmorMs=0; this.airHeight=0; this.verticalVelocity=0; this.blockHeld=false; this.stateMachine.transition('dead'); this.setVelocity(0); }
  receiveKnockback(from: Phaser.Math.Vector2, power:number): void { if(this.stateMachine.state==='dead' || power<=0) return; applyKnockback(this,from,power,1); }
  resetState(x:number,y:number):void{this.setPosition(x,y);this.setVelocity(0);this.health=this.maxHealth;this.guard=COMBAT_CONFIG.guardMax;this.invulnerableMs=0;this.superArmorMs=0;this.airHeight=0;this.verticalVelocity=0;this.blockStartedAt=-Infinity;this.blockHeld=false;this.facing.set(1,0);this.stateMachine=new CombatStateMachine();this.enableBody(false,x,y,true,true);}
  private textureForState(): string { if(this.stateMachine.state==='blocking')return 'player-block'; if(this.stateMachine.state==='attacking'||this.stateMachine.state==='countering')return 'player-attack'; if(this.stateMachine.state==='stunned')return 'player-stun'; if(this.stateMachine.state==='knockedDown')return 'player-down'; if(this.stateMachine.state==='dead')return 'player-down'; return 'player-idle'; }
}
