import { ARENA } from '../constants/game.constants';
import { Player } from '../actors/Player';
import { Enemy } from '../actors/Enemy';
import { InputController } from '../input/InputController';
import { BasicCombatController } from '../combat/BasicCombatController';
import { COMBAT_CONFIG } from '../data/combatConfig';
import { AsteriaArena } from '../world/AsteriaArena';
import { CombatHud } from '../ui/CombatHud';
import { CombatDebugOverlay } from '../debug/CombatDebugOverlay';
import type { ArenaStatus } from '../types/game.types';
export class CombatScene extends Phaser.Scene { private player!: Player; private enemies: Enemy[]=[]; private inputController!: InputController; private combat!: BasicCombatController; private arena!: AsteriaArena; private hud!: CombatHud; private debug!: CombatDebugOverlay; private status: ArenaStatus='Fighting'; constructor(){super('CombatScene');}
  create(): void { this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.cleanup()); this.physics.world.setBounds(ARENA.left,ARENA.top,ARENA.right-ARENA.left,ARENA.bottom-ARENA.top); this.arena=new AsteriaArena(this); this.arena.build(); this.player=new Player(this,640,520); this.combat=new BasicCombatController(this); this.inputController=new InputController(this); this.hud=new CombatHud(); this.debug=new CombatDebugOverlay(this); this.spawnEnemies(); this.physics.add.collider(this.player,this.arena.obstacles); this.enemies.forEach(e=>{this.physics.add.collider(e,this.arena.obstacles); this.physics.add.collider(e,this.player,()=>undefined,()=>false);}); }
  update(time:number, delta:number): void { const input=this.inputController.getState(); if(input.restart){ this.scene.restart(); return; } if(input.debug) this.debug.toggle(); this.player.updatePlayer(input,delta,time); if(this.player.stateMachine.state!=='dead'){ if(input.dodge) this.combat.requestDodge(this.player,input); if(input.attack) this.combat.requestAttack(this.player); if(input.skill) this.combat.requestSkill(this.player); } this.updateEnemies(delta); this.combat.update(this.player,this.enemies.filter(e=>e.active),delta,time); this.inputController.clearMomentaryTouch(); const remaining=this.enemies.filter(e=>e.active).length; if(remaining===0 && this.status==='Fighting'){this.status='Completed'; this.arena.openDoor();} if(this.player.health<=0 && this.status==='Fighting'){ this.status='Defeated'; this.combat.onPlayerDefeated(); } this.hud.update({health:this.player.health,maxHealth:this.player.maxHealth,guard:this.player.guard,maxGuard:COMBAT_CONFIG.guardMax,state:this.player.stateMachine.state,attackPhase:this.combat.playerAttack.phase,enemiesRemaining:remaining,combo:this.combat.combo,score:this.combat.score,skillCooldown:this.combat.skillCooldown,dodgeCooldown:this.combat.dodge.cooldownMs,counterReady:this.combat.counter.isReady,status:this.status}); this.debug.update(this.player,this.enemies,this.combat); }
  private updateEnemies(delta:number): void { for(const e of this.enemies){ if(!e.active) continue; e.updateEnemy(delta); const dir=new Phaser.Math.Vector2(this.player.x-e.x,this.player.y-e.y); const dist=dir.length(); if(dist>0) e.facing.copy(dir.normalize()); if(['stunned','airborne','knockedDown','attacking'].includes(e.stateMachine.state)){ e.setVelocity(0); continue; } if(e.aiState==='Telegraph') { e.setVelocity(0); continue; } if(this.player.stateMachine.state==='dead'){ e.setVelocity(0); continue; } if(dist<e.config.attackRange+18 && e.attackCooldown<=0){ if(!this.combat.startEnemyTelegraph(e,true)){ e.aiState='Position'; const side=new Phaser.Math.Vector2(-e.facing.y,e.facing.x); this.physics.moveTo(e,e.x+side.x*80,e.y+side.y*80,e.config.speed*0.75); } } else if(dist>e.config.attackRange){ e.aiState='Approach'; this.physics.moveToObject(e,this.player,e.config.speed); } else { e.aiState='Position'; e.setVelocity(-e.facing.x*35,e.facing.y*20); } } }
  private cleanup(): void { this.hud?.destroy(); this.debug?.destroy(); this.inputController?.destroy(); this.combat?.reset(); this.enemies.forEach(e=>e.telegraph?.destroy()); }
  private spawnEnemies(): void { const data: Array<[number,number,'normal'|'heavy']> = [[320,180,'normal'],[960,180,'normal'],[310,560,'normal'],[980,560,'normal'],[640,210,'heavy']]; this.enemies=data.map(([x,y,v],i)=>new Enemy(this,x,y,v,450+i*220)); }
}
