export type AssetKind = 'spritesheet' | 'image' | 'tilemap' | 'atlasMetadata';
export interface AnimationCombatSync { animationKey:string; startupEndFrame:number; activeStartFrame:number; activeEndFrame:number; recoveryEndFrame:number; hitFrames?:number[]; movementFrames?: { frame:number; offsetX:number; offsetY:number }[]; fallbackMs:number; finishSkillAuthoritative?: boolean }
export interface AnimationDefinition { key:string; assetKey:string; frames:number[]; frameRate:number; repeat:number; durationMs:number; sync?:AnimationCombatSync; visibleWeapons?: readonly ('left'|'right')[]; actionHand?: 'left'|'right'|'both' }
export interface AssetDefinition { key:string; path:string; kind:AssetKind; critical:boolean; frameWidth?:number; frameHeight?:number; atlasJson?:string; scale:number; origin:[number,number]; animations?:AnimationDefinition[]; notes?:string }
const kaelAction=(key:string,frames:number[],hand:'left'|'right'|'both',hits:number[]):AnimationDefinition=>({key,assetKey:'kael-atlas',frames,frameRate:12,repeat:0,durationMs:frames.length*83,visibleWeapons:hand==='both'?['left','right']:[hand],actionHand:hand,sync:{animationKey:key,startupEndFrame:frames[0],activeStartFrame:frames[0],activeEndFrame:frames[frames.length-1],recoveryEndFrame:frames[frames.length-1],hitFrames:hits,fallbackMs:frames.length*83,finishSkillAuthoritative:true}});
export const KAEL_REQUIRED_ANIMATIONS=['kael-idle-down','kael-idle-up','kael-idle-left','kael-idle-right','kael-run-down','kael-run-up','kael-run-left','kael-run-right','kael-block','kael-perfect-block','kael-dodge','kael-hit','kael-stunned','kael-airborne','kael-knockdown','kael-get-up','kael-dead','kael-twin-slash-1','kael-twin-slash-2','kael-cross-cut','kael-rising-fang','kael-falling-edge','kael-rising-tempest','kael-phantom-rush','kael-blade-cyclone','kael-sky-reaver','kael-flash-execution','kael-falling-judgment','kael-counter'] as const;
export const kaelAnimations: AnimationDefinition[]=[
  ...['down','up','left','right'].flatMap((d,i)=>[{key:`kael-idle-${d}`,assetKey:'kael-atlas',frames:[i*2,i*2+1],frameRate:4,repeat:-1,durationMs:500,visibleWeapons:['left','right'] as const},{key:`kael-run-${d}`,assetKey:'kael-atlas',frames:[8+i*2,9+i*2],frameRate:8,repeat:-1,durationMs:250,visibleWeapons:['left','right'] as const}]),
  kaelAction('kael-block',[16,17], 'both',[17]), kaelAction('kael-perfect-block',[18,19], 'both',[19]), kaelAction('kael-dodge',[20,21,22], 'both',[21]), kaelAction('kael-hit',[23,24], 'both',[23]), kaelAction('kael-stunned',[25,26], 'both',[25]), kaelAction('kael-airborne',[27,28], 'both',[28]), kaelAction('kael-knockdown',[29,30], 'both',[30]), kaelAction('kael-get-up',[31,32], 'both',[32]), kaelAction('kael-dead',[33], 'both',[33]),
  kaelAction('kael-twin-slash-1',[34,35,36],'right',[35]), kaelAction('kael-twin-slash-2',[36,37,38],'left',[37]), kaelAction('kael-cross-cut',[38,39,40,41],'both',[39,40]), kaelAction('kael-rising-fang',[40,41,42],'both',[41]), kaelAction('kael-falling-edge',[42,43,44],'both',[43]),
  kaelAction('kael-rising-tempest',[34,35,36,37,38],'both',[35,37]), kaelAction('kael-phantom-rush',[36,37,38,39,40,41],'both',[37,39,41]), kaelAction('kael-blade-cyclone',[40,41,42,43,44,45],'both',[41,42,43,44]),
  kaelAction('kael-sky-reaver',[35,36,37],'both',[36]), kaelAction('kael-flash-execution',[38,39,40,41],'both',[39,40]), kaelAction('kael-falling-judgment',[42,43,44],'both',[43]), kaelAction('kael-counter',[16,18,39,40],'both',[39,40])
];
export const enemyAnimations: AnimationDefinition[]=['soldier','brute'].flatMap((p)=>['idle','run','telegraph','attack','recover','hit','stun','airborne','knockdown','get-up','dead','heavy-attack','unblockable-attack','stagger'].map((s,i)=>({key:`${p}-${s}`,assetKey:p==='soldier'?'soldier-atlas':'brute-atlas',frames:[i*2%48,(i*2+1)%48],frameRate:s==='idle'?4:8,repeat:s==='idle'||s==='run'?-1:0,durationMs:250,sync:s.includes('attack')||s==='telegraph'?{animationKey:`${p}-${s}`,startupEndFrame:0,activeStartFrame:1,activeEndFrame:1,recoveryEndFrame:1,hitFrames:s.includes('attack')?[1]:[],fallbackMs:250}:undefined})));
export const assetManifest={ artDirection:{style:'stylized high-resolution painted placeholder raster, top-down 2.5D',tileSize:64,pixelArt:false,filtering:'linear'}, assets:[
 {key:'kael-atlas',path:'assets/characters/kael/kael-atlas.png',kind:'spritesheet',critical:true,frameWidth:128,frameHeight:128,atlasJson:'assets/characters/kael/kael-atlas.json',scale:1,origin:[.5,.85] as [number,number],animations:kaelAnimations,notes:'original provisional raster dual-wield sheet'},
 {key:'soldier-atlas',path:'assets/enemies/corrupted-soldier/soldier-atlas.png',kind:'spritesheet',critical:true,frameWidth:128,frameHeight:128,atlasJson:'assets/enemies/corrupted-soldier/soldier-atlas.json',scale:1,origin:[.5,.85] as [number,number],animations:enemyAnimations.filter(a=>a.assetKey==='soldier-atlas')},
 {key:'brute-atlas',path:'assets/enemies/stone-brute/brute-atlas.png',kind:'spritesheet',critical:true,frameWidth:128,frameHeight:128,atlasJson:'assets/enemies/stone-brute/brute-atlas.json',scale:1.45,origin:[.5,.85] as [number,number],animations:enemyAnimations.filter(a=>a.assetKey==='brute-atlas')},
 {key:'asteria-tiles',path:'assets/environments/asteria/asteria-tileset.png',kind:'image',critical:true,scale:1,origin:[0,0] as [number,number]},{key:'asteria-map',path:'assets/environments/asteria/asteria-map.json',kind:'tilemap',critical:true,scale:1,origin:[0,0] as [number,number]},
 ...['sword-effects-atlas','status-effects-atlas','telegraph-atlas','shadows-atlas','props-atlas'].map(key=>({key,path:`assets/effects/${key}.png`,kind:'spritesheet' as const,critical:true,frameWidth:128,frameHeight:128,atlasJson:`assets/effects/${key}.json`,scale:1,origin:[.5,.5] as [number,number]})),
 ...[{key:'kael-portrait',path:'assets/characters/kael/kael-portrait.png'},{key:'kael-icons',path:'assets/characters/kael/kael-icons.png'},{key:'skill-icons',path:'assets/ui/skill-icons.png'},{key:'hud-frame',path:'assets/ui/hud-frame.png'},{key:'character-select-panel',path:'assets/ui/character-select.png'},{key:'missing-texture',path:'assets/debug/missing-texture.png'}].map(a=>({...a,kind:'image' as const,critical:true,scale:1,origin:[.5,.5] as [number,number]}))
] as AssetDefinition[]};
export const getAnimation=(key:string): AnimationDefinition|undefined=>assetManifest.assets.flatMap(a=>a.animations??[]).find(a=>a.key===key);
